### ISSUE TITLE
Error when trying to run exemple

### ISSUE THREAD

**Issue by redam** [jxsl13/twapi#6]
Hello,
I'm trying to find a command line tool to get teeworlds server info, your code might just be what I'm looking for but when I try to run your example I get this error :
```
# github.com/jxsl13/twapi/compression
../go/src/github.com/jxsl13/twapi/compression/varint.go:78: syntax error: unexpected b00000001, expecting comma or )
../go/src/github.com/jxsl13/twapi/compression/varint.go:79: syntax error: unexpected b00111111, expecting comma or )
../go/src/github.com/jxsl13/twapi/compression/varint.go:83: syntax error: missing { after if clause
../go/src/github.com/jxsl13/twapi/compression/varint.go:84: syntax error: unexpected break, expecting expression
```

Code :
```
package main

import (
    "fmt"
    "github.com/jxsl13/twapi/browser"
)

func main() {
    // fetch all server infos (that respond within 16 seconds)
    // if no servers responded, this list will be empty.
    infos := browser.ServerInfos()
    for _, info := range infos {
        fmt.Println(info)
    }

    // fetches the specified server's players, server name, etc.
    // if no answer is received within 16 seconds, this function returns
    // an error
    info, err := browser.GetServerInfo("89.163.148.121", 8305)
    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println(info)
    }
}
```
As I've never used go, I might be completely wrong on how to run a go program...

**Comment by jxsl13** [comment]
Will look into it tomorrow evening (today evening, actually)

**Comment by jxsl13** [comment]
general usage is:
you download the go compiler/toolchain
create a folder
cd into the folder
execute: `go mod init test`
touch main.go
put the example code into main.go
iirc, occasionally a `go get -d`
and lastly : `go build .`
execute with: `./main`

**Comment by jxsl13** [comment]
well, I tested it and used the easy way to test this: https://play.golang.org/p/ZOoMvjNXwR9
and it worked.

My guess is that your Go version might be below 1.13, which is required for this package, 
as those binary literals `b00000001` were introduced in Go 1.13

```shell
$ go version
go version go1.15.3 darwin/amd64
```

**Comment by jxsl13** [comment]
Here is an example project that works for me:
[go-test.zip](https://github.com/jxsl13/twapi/files/5584415/go-test.zip)

**Comment by redam** [comment]
Thank you for your help, you were right I was using an old version of go : 1.9 on debian oldstable, then 1.11 on debian stable, finally working on debian testing with 1.15 :)
What would have been great is an output a little more structured to be able to process it on the command line. I've changed your example to fmt.Printf("%+v",info), it's a little better but as I don't know anything about Go I guess there must be a really better way than this to have for example a nice JSON output. Anyway it should be enough for me, thank you for your code :+1:

**Comment by redam** [comment]
Ok found "encoding/json" library(?) that does exactly that, perfect :+1:

**Comment by jxsl13** [comment]
json.MarshalIndented iirc might help.

**Comment by jxsl13** [comment]
well, all I do there is take the struct (class) and create a json string out of it. you can create a type alias and extend the struct's functions, e.g. add a function that simply outputs a single line string.

**Comment by jxsl13** [comment]
there is a command line tool that is called 'jq' which can process JSON on the command line, tho I have not learned its syntax myself, yet.
